### ISSUE TITLE
Agree on Project and setup IAM

### ISSUE THREAD

**Issue by ldb** [mindtastic/infrastructure#10]
As of now, all development has been done in an ad-hoc way using different projects.
This must be consolidated going forward, using a single Google Cloud Project for all of use.
Besides that, all of us need access granted to that project using IAM.

**Comment by ldb** [comment]
Terraform Cloud has a service account, that needs to be able to fully control Kubernetes using the Kubernetes Editor (or Owner) role.

**Comment by jgraeger** [comment]
Today we agreed on using my GCP project (mindtastic-349106). 
I've added/changed the coressponding variables in terraform cloud.
All members of our organization should have access with the GCP predefined "Editor" role.

However, we still use a predefined service account for terraform cloud which is used for everything (it therefore not only needs a predfined role with wide access, but also a kubernetes cluster admin role). We should also setup a new service account for the deployment in code. I will extract a seperate issue.

**Comment by jgraeger** [comment]
Closing the issue as mentioned before.
