### ISSUE TITLE
Make Cluster private

### ISSUE THREAD

**Issue by ldb** [mindtastic/infrastructure#2]
Right now we have a GKE cluster that is public to the internet.
We should switch to using a [_private_](https://cloud.google.com/kubernetes-engine/docs/how-to/private-clusters), [_VPC-native_](https://cloud.google.com/kubernetes-engine/docs/concepts/alias-ips#default_cluster_network_mode) cluster instead.

We can take care of access to this cluster later. For now making it private is the only priority.

**Comment by jgraeger** [comment]
I've just pushed a development branch [feature/private-cluster](https://github.com/mindtastic/infrastructure/tree/feature/private-cluster). However I will not created a pull request yet, since that might cause execution in terraform cloud.

**Comment by jgraeger** [comment]
PR is ready to be reviewed :)
