### ISSUE TITLE
Fix ArgoCD Healthchecks for Traefik Ingress

### ISSUE THREAD

**Issue by ldb** [mindtastic/infrastructure#65]
Due to the way Traefik Ingress presents itself to the Kubernetes API, ArgoCD does never consider it to be in a 'healthy' state.

This can be fixed by deploying a custom Healthcheck in Argo for Traefik Ingress:

https://argo-cd.readthedocs.io/en/stable/operator-manual/health/

**Comment by jgraeger** [comment]
This will be fixed in the traefik deployment mindtastic/deployments#26.
