### ISSUE TITLE
Setup DNS

### ISSUE THREAD

**Issue by ldb** [mindtastic/infrastructure#9]
We bought the `mindtastic.lol` domain on Namecheap. We must federate this to Google Cloud DNS.
There should also exist an initial top level zone under `net.mindtastic.lol` that will hold all infrastructure related domains. Besides that, `api.mindtastic.lol` can be created for service APIs.
Each of these zones should contain an additional sub zone `live.` indicating production traffic. This will allow us to later easily integrate other environments in a consistent way.

**Comment by jgraeger** [comment]
As @ldb mentioned: Done by merging PR #15
